### ISSUE TITLE
Teacher Week 4 Review

### ISSUE THREAD

**Issue by dtsivkovski** [dtsivkovski/PMB-Portfolio#13]

**Comment by jm1021** [comment]
They want to figure out randomization, not ticket yet.    Tickets are not filled out to my expectation presently.  .5 /1.0

**Comment by LindaLiu1202** [comment]
Individually, the review in the videos was clear; everyone showed what they did and what commits they have. However, the videos are not in a YouTube playlist or something and also only 3 of the videos were numbered, which make them hard for me to watch since I have to click and open the videos individually.

**Comment by LindaLiu1202** [comment]
Score: 4.25 maximum, still need individual review

**Comment by LindaLiu1202** [comment]
Individual review done. Everyone contributed and did commits on meaningful tasks. The score is 4.25 for everyone.
